In [1]:
# Project Setup

from pathlib import Path
import os
import sys

PROJECT_ROOT = Path(os.getcwd()).resolve().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
# Imports

import importlib
import pandas as pd

import src.feature_engineering as fe

importlib.reload(fe)

from src.feature_engineering import (
    _validate_dataframe,
    _validate_columns_exist,
    get_numerical_columns,
)

In [3]:
# =============================================================================
# Load Dataset
# =============================================================================

from pathlib import Path

from src.preprocessing import load_dataset

DATA_PATH = Path("../data/interim/cleaned_data.csv").resolve()

df = load_dataset(DATA_PATH)

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [4]:
# =============================================================================
# Dataset Information
# =============================================================================

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

df.info()

Rows    : 32416
Columns : 12
<class 'pandas.DataFrame'>
RangeIndex: 32416 entries, 0 to 32415
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32416 non-null  int64
 1   person_income               32416 non-null  int64
 2   person_home_ownership       32416 non-null  str
 3   person_emp_length           32416 non-null  float64
 4   loan_intent                 32416 non-null  str
 5   loan_grade                  32416 non-null  str
 6   loan_amnt                   32416 non-null  int64
 7   loan_int_rate               32416 non-null  float64
 8   loan_status                 32416 non-null  int64
 9   loan_percent_income         32416 non-null  float64
 10  cb_person_default_on_file   32416 non-null  str
 11  cb_person_cred_hist_length  32416 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [5]:
# =============================================================================
# Test : _validate_dataframe()
# =============================================================================

_validate_dataframe(df)

print("✅ _validate_dataframe() Passed")

✅ _validate_dataframe() Passed

In [6]:
# =============================================================================
# Test : _validate_columns_exist()
# =============================================================================

_validate_columns_exist(
    df,
    ["loan_status"]
)

print("✅ _validate_columns_exist() Passed")

✅ _validate_columns_exist() Passed

In [7]:
# =============================================================================
# Test : get_numerical_columns()
# =============================================================================

numerical_columns = get_numerical_columns(
    dataframe=df,
    target_column="loan_status"
)

print(f"Numerical Columns ({len(numerical_columns)}):")
print(numerical_columns)

Numerical Columns (7):
['person_age', 'person_income', 'person_emp_length', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']

## Numerical Feature Summary

The function successfully identified all numerical feature columns after excluding the target column. These columns will be used for numerical preprocessing in the upcoming pipeline.

In [8]:
from src.feature_engineering import get_categorical_columns

categorical_columns = get_categorical_columns(
    dataframe=df,
    target_column="loan_status"
)

print(categorical_columns)

['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']

In [9]:
categorical_columns = get_categorical_columns(
    dataframe=df,
    target_column="loan_status",
    excluded_columns=["loan_grade"]
)

print(categorical_columns)

['person_home_ownership', 'loan_intent', 'cb_person_default_on_file']

In [10]:
get_categorical_columns(
    dataframe=df,
    target_column="default_status"
)

ValueError: The following required columns are missing from the DataFrame: ['default_status']

In [11]:
get_categorical_columns(
    dataframe=df,
    target_column="loan_status",
    excluded_columns=["loan_grade", 10]
)

TypeError: All values in 'excluded_columns' must be strings.

In [12]:
from src.feature_engineering import split_features_target
from src.config import TARGET_COLUMN

In [13]:
X, y = split_features_target(
    dataframe=df,
    target_column=TARGET_COLUMN
)

In [14]:
print("Feature Matrix Shape :", X.shape)
print("Target Vector Shape  :", y.shape)

Feature Matrix Shape : (32416, 11)
Target Vector Shape  : (32416,)

In [15]:
split_features_target(
    dataframe=df,
    target_column="default_status"
)

ValueError: The following required columns are missing from the DataFrame: ['default_status']

In [16]:
split_features_target(
    dataframe=df,
    target_column=10
)

TypeError: Expected 'target_column' to be a string.

# Train, Validation and Test Split

In [17]:
from src.feature_engineering import split_dataset

In [18]:
(
    X_train,
    X_validation,
    X_test,
    y_train,
    y_validation,
    y_test,
) = split_dataset(
    X,
    y,
)

In [19]:
print("Training Set")
print(X_train.shape)
print(y_train.shape)

print()

print("Validation Set")
print(X_validation.shape)
print(y_validation.shape)

print()

print("Test Set")
print(X_test.shape)
print(y_test.shape)

Training Set
(20745, 11)
(20745,)

Validation Set
(5187, 11)
(5187,)

Test Set
(6484, 11)
(6484,)

In [20]:
print("Original Distribution")
print(df["loan_status"].value_counts(normalize=True))

print()

print("Training Distribution")
print(y_train.value_counts(normalize=True))

print()

print("Validation Distribution")
print(y_validation.value_counts(normalize=True))

print()

print("Test Distribution")
print(y_test.value_counts(normalize=True))

Original Distribution
loan_status
0    0.781312
1    0.218688
Name: proportion, dtype: float64

Training Distribution
loan_status
0    0.781297
1    0.218703
Name: proportion, dtype: float64

Validation Distribution
loan_status
0    0.781377
1    0.218623
Name: proportion, dtype: float64

Test Distribution
loan_status
0    0.781308
1    0.218692
Name: proportion, dtype: float64

In [21]:
X_train.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
4846,23,30000,RENT,7.0,PERSONAL,C,5000,14.17,0.17,Y,3
20435,29,96500,RENT,13.0,PERSONAL,B,10000,8.88,0.10,N,8
22396,35,50000,RENT,6.0,VENTURE,B,7200,11.99,0.14,N,9
9428,22,62000,MORTGAGE,2.0,EDUCATION,A,10000,5.99,0.16,N,4
22032,32,52800,MORTGAGE,2.0,HOMEIMPROVEMENT,A,24000,7.51,0.45,N,10

In [22]:
y_train.head()

4846     1
20435    0
22396    0
9428     0
22032    0
Name: loan_status, dtype: int64

In [23]:
from src.feature_engineering import build_preprocessor

In [24]:
preprocessor = build_preprocessor(
    numerical_columns=numerical_columns,
    categorical_columns=categorical_columns,
)

In [25]:
preprocessor

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['person_age', 'person_income',
                                  'person_emp_length', 'loan_amnt',
                                  'loan_int_rate', 'loan_percent_income',
                                  'cb_person_cred_hist_length']),
                                ('categorical',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['person_home_ownership', 'loan_intent',
                                  'cb_person_default_on_file'])])

In [26]:
type(preprocessor)

sklearn.compose._column_transformer.ColumnTransformer

# Fit Preprocessing Pipeline

In [27]:
from src.feature_engineering import fit_preprocessor

In [28]:
preprocessor = fit_preprocessor(
    preprocessor=preprocessor,
    X_train=X_train,
)

In [31]:
preprocessor

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['person_age', 'person_income',
                                  'person_emp_length', 'loan_amnt',
                                  'loan_int_rate', 'loan_percent_income',
                                  'cb_person_cred_hist_length']),
                                ('categorical',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['person_home_ownership', 'loan_intent',
                                  'cb_person_default_on_file'])])

In [32]:
type(preprocessor)

sklearn.compose._column_transformer.ColumnTransformer

In [33]:
print(preprocessor)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['person_age', 'person_income',
                                  'person_emp_length', 'loan_amnt',
                                  'loan_int_rate', 'loan_percent_income',
                                  'cb_person_cred_hist_length']),
                                ('categorical',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['person_home_ownership', 'loan_intent',
                                  'cb_person_default_on_file'])])

# Transform Dataset

In [34]:
from src.feature_engineering import transform_dataset

In [35]:
(
    X_train_processed,
    X_validation_processed,
    X_test_processed,
) = transform_dataset(
    preprocessor=preprocessor,
    X_train=X_train,
    X_validation=X_validation,
    X_test=X_test,
)

In [36]:
print("=" * 60)
print("Processed Dataset Shapes")
print("=" * 60)

print("Training :", X_train_processed.shape)
print("Validation :", X_validation_processed.shape)
print("Test :", X_test_processed.shape)

============================================================
Processed Dataset Shapes
============================================================
Training : (20745, 19)
Validation : (5187, 19)
Test : (6484, 19)

In [37]:
X_train_processed.head()

,numerical__person_age,numerical__person_income,numerical__person_emp_length,numerical__loan_amnt,numerical__loan_int_rate,numerical__loan_percent_income,numerical__cb_person_cred_hist_length,categorical__person_home_ownership_MORTGAGE,categorical__person_home_ownership_OTHER,categorical__person_home_ownership_OWN,categorical__person_home_ownership_RENT,categorical__loan_intent_DEBTCONSOLIDATION,categorical__loan_intent_EDUCATION,categorical__loan_intent_HOMEIMPROVEMENT,categorical__loan_intent_MEDICAL,categorical__loan_intent_PERSONAL,categorical__loan_intent_VENTURE,categorical__cb_person_default_on_file_N,categorical__cb_person_default_on_file_Y
4846,-0.744960,-0.542319,0.544813,-0.729132,1.024433,-0.002730,-0.691507,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
20435,0.197992,0.458352,1.999275,0.065639,-0.693404,-0.658978,0.542647,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
22396,1.140944,-0.241366,0.302402,-0.379433,0.316516,-0.283979,0.789478,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9428,-0.902119,-0.060794,-0.667239,0.065639,-1.631882,-0.096479,-0.444676,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
22032,0.669468,-0.199232,-0.667239,2.290999,-1.138288,2.622264,1.036309,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [38]:
print(X_train_processed.columns.tolist())

['numerical__person_age', 'numerical__person_income', 'numerical__person_emp_length', 'numerical__loan_amnt', 'numerical__loan_int_rate', 'numerical__loan_percent_income', 'numerical__cb_person_cred_hist_length', 'categorical__person_home_ownership_MORTGAGE', 'categorical__person_home_ownership_OTHER', 'categorical__person_home_ownership_OWN', 'categorical__person_home_ownership_RENT', 'categorical__loan_intent_DEBTCONSOLIDATION', 'categorical__loan_intent_EDUCATION', 'categorical__loan_intent_HOMEIMPROVEMENT', 'categorical__loan_intent_MEDICAL', 'categorical__loan_intent_PERSONAL', 'categorical__loan_intent_VENTURE', 'categorical__cb_person_default_on_file_N', 'categorical__cb_person_default_on_file_Y']

In [39]:
type(X_train_processed)

pandas.DataFrame

# Save and Load Preprocessor

In [40]:
from src.feature_engineering import (
    save_pickle,
    load_pickle,
)

from src.config import SCALER_PATH

In [41]:
save_pickle(
    object_to_save=preprocessor,
    file_path=SCALER_PATH,
)

In [42]:
loaded_preprocessor = load_pickle(
    SCALER_PATH,
)

In [43]:
type(loaded_preprocessor)

sklearn.compose._column_transformer.ColumnTransformer

In [44]:
print(loaded_preprocessor)

ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['person_age', 'person_income',
                                  'person_emp_length', 'loan_amnt',
                                  'loan_int_rate', 'loan_percent_income',
                                  'cb_person_cred_hist_length']),
                                ('categorical',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['person_home_ownership', 'loan_intent',
                                  'cb_person_default_on_file'])])

# Final Verification

In [45]:
print("=" * 80)
print("TRAIN DATASET")
print("=" * 80)

X_train_processed.info()

print("\n")

print("=" * 80)
print("VALIDATION DATASET")
print("=" * 80)

X_validation_processed.info()

print("\n")

print("=" * 80)
print("TEST DATASET")
print("=" * 80)

X_test_processed.info()

================================================================================
TRAIN DATASET
================================================================================
<class 'pandas.DataFrame'>
Index: 20745 entries, 4846 to 16121
Data columns (total 19 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   numerical__person_age                        20745 non-null  float64
 1   numerical__person_income                     20745 non-null  float64
 2   numerical__person_emp_length                 20745 non-null  float64
 3   numerical__loan_amnt                         20745 non-null  float64
 4   numerical__loan_int_rate                     20745 non-null  float64
 5   numerical__loan_percent_income               20745 non-null  float64
 6   numerical__cb_person_cred_hist_length        20745 non-null  float64
 7   categorical__person_home_ownership_MORTGAGE  20745 non-null  float64
 8   categorical__person_home_ownership_OTHER     20745 non-null  float64
 9   categorical__person_home_ownership_OWN       20745 non-null  float64
 10  categorical__person_home_ownership_RENT      20745 non-null  float64
 11  categorical__loan_intent_DEBTCONSOLIDATION   20745 non-null  float64
 12  categorical__loan_intent_EDUCATION           20745 non-null  float64
 13  categorical__loan_intent_HOMEIMPROVEMENT     20745 non-null  float64
 14  categorical__loan_intent_MEDICAL             20745 non-null  float64
 15  categorical__loan_intent_PERSONAL            20745 non-null  float64
 16  categorical__loan_intent_VENTURE             20745 non-null  float64
 17  categorical__cb_person_default_on_file_N     20745 non-null  float64
 18  categorical__cb_person_default_on_file_Y     20745 non-null  float64
dtypes: float64(19)
memory usage: 3.2 MB


================================================================================
VALIDATION DATASET
================================================================================
<class 'pandas.DataFrame'>
Index: 5187 entries, 30294 to 18085
Data columns (total 19 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   numerical__person_age                        5187 non-null   float64
 1   numerical__person_income                     5187 non-null   float64
 2   numerical__person_emp_length                 5187 non-null   float64
 3   numerical__loan_amnt                         5187 non-null   float64
 4   numerical__loan_int_rate                     5187 non-null   float64
 5   numerical__loan_percent_income               5187 non-null   float64
 6   numerical__cb_person_cred_hist_length        5187 non-null   float64
 7   categorical__person_home_ownership_MORTGAGE  5187 non-null   float64
 8   categorical__person_home_ownership_OTHER     5187 non-null   float64
 9   categorical__person_home_ownership_OWN       5187 non-null   float64
 10  categorical__person_home_ownership_RENT      5187 non-null   float64
 11  categorical__loan_intent_DEBTCONSOLIDATION   5187 non-null   float64
 12  categorical__loan_intent_EDUCATION           5187 non-null   float64
 13  categorical__loan_intent_HOMEIMPROVEMENT     5187 non-null   float64
 14  categorical__loan_intent_MEDICAL             5187 non-null   float64
 15  categorical__loan_intent_PERSONAL            5187 non-null   float64
 16  categorical__loan_intent_VENTURE             5187 non-null   float64
 17  categorical__cb_person_default_on_file_N     5187 non-null   float64
 18  categorical__cb_person_default_on_file_Y     5187 non-null   float64
dtypes: float64(19)
memory usage: 810.5 KB


================================================================================
TEST DATASET
================================================================================
<class 'pandas.DataFrame'>
Index: 6484 entries, 21156 to 30437
Data columns (total 19 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   numerical__person_age                        6484 non-null   float64
 1   numerical__person_income                     6484 non-null   float64
 2   numerical__person_emp_length                 6484 non-null   float64
 3   numerical__loan_amnt                         6484 non-null   float64
 4   numerical__loan_int_rate                     6484 non-null   float64
 5   numerical__loan_percent_income               6484 non-null   float64
 6   numerical__cb_person_cred_hist_length        6484 non-null   float64
 7   categorical__person_home_ownership_MORTGAGE  6484 non-null   float64
 8   categorical__person_home_ownership_OTHER     6484 non-null   float64
 9   categorical__person_home_ownership_OWN       6484 non-null   float64
 10  categorical__person_home_ownership_RENT      6484 non-null   float64
 11  categorical__loan_intent_DEBTCONSOLIDATION   6484 non-null   float64
 12  categorical__loan_intent_EDUCATION           6484 non-null   float64
 13  categorical__loan_intent_HOMEIMPROVEMENT     6484 non-null   float64
 14  categorical__loan_intent_MEDICAL             6484 non-null   float64
 15  categorical__loan_intent_PERSONAL            6484 non-null   float64
 16  categorical__loan_intent_VENTURE             6484 non-null   float64
 17  categorical__cb_person_default_on_file_N     6484 non-null   float64
 18  categorical__cb_person_default_on_file_Y     6484 non-null   float64
dtypes: float64(19)
memory usage: 1013.1 KB

In [46]:
print("=" * 80)
print("Missing Values")
print("=" * 80)

print("Train      :", X_train_processed.isna().sum().sum())
print("Validation :", X_validation_processed.isna().sum().sum())
print("Test       :", X_test_processed.isna().sum().sum())

================================================================================
Missing Values
================================================================================
Train      : 0
Validation : 0
Test       : 0

In [47]:
print("=" * 80)
print("Processed Dataset Shapes")
print("=" * 80)

print("Training    :", X_train_processed.shape)
print("Validation  :", X_validation_processed.shape)
print("Test        :", X_test_processed.shape)

================================================================================
Processed Dataset Shapes
================================================================================
Training    : (20745, 19)
Validation  : (5187, 19)
Test        : (6484, 19)

In [48]:
print("=" * 80)
print("Feature Names")
print("=" * 80)

for column in X_train_processed.columns:
    print(column)

================================================================================
Feature Names
================================================================================
numerical__person_age
numerical__person_income
numerical__person_emp_length
numerical__loan_amnt
numerical__loan_int_rate
numerical__loan_percent_income
numerical__cb_person_cred_hist_length
categorical__person_home_ownership_MORTGAGE
categorical__person_home_ownership_OTHER
categorical__person_home_ownership_OWN
categorical__person_home_ownership_RENT
categorical__loan_intent_DEBTCONSOLIDATION
categorical__loan_intent_EDUCATION
categorical__loan_intent_HOMEIMPROVEMENT
categorical__loan_intent_MEDICAL
categorical__loan_intent_PERSONAL
categorical__loan_intent_VENTURE
categorical__cb_person_default_on_file_N
categorical__cb_person_default_on_file_Y

In [49]:
X_train_processed.describe().T

,count,mean,std,min,25%,50%,75%,max
numerical__person_age,20745.0,1.335800e-16,1.000024,-1.216436,-0.744960,-0.273484,0.355151,18.271241
numerical__person_income,20745.0,-1.164543e-17,1.000024,-0.933559,-0.414414,-0.166127,0.195017,89.292348
numerical__person_emp_length,20745.0,1.013838e-16,1.000024,-1.152060,-0.667239,-0.182418,0.544813,28.664420
numerical__loan_amnt,20745.0,-1.400877e-16,1.000024,-1.444426,-0.729132,-0.252269,0.431234,4.039496
numerical__loan_int_rate,20745.0,-3.699138e-17,1.000024,-1.816979,-0.820049,-0.008217,0.680216,3.963265
numerical__loan_percent_income,20745.0,2.226333e-17,1.000024,-1.596475,-0.752728,-0.190229,0.559769,5.716005
numerical__cb_person_cred_hist_length,20745.0,-3.767640e-17,1.000024,-0.938338,-0.691507,-0.444676,0.542647,5.972926
categorical__person_home_ownership_MORTGAGE,20745.0,4.149916e-01,0.492732,0.000000,0.000000,0.000000,1.000000,1.000000
categorical__person_home_ownership_OTHER,20745.0,3.470716e-03,0.058812,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__person_home_ownership_OWN,20745.0,7.905519e-02,0.269831,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__person_home_ownership_RENT,20745.0,5.024825e-01,0.500006,0.000000,0.000000,1.000000,1.000000,1.000000
categorical__loan_intent_DEBTCONSOLIDATION,20745.0,1.604242e-01,0.367008,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__loan_intent_EDUCATION,20745.0,1.976380e-01,0.398227,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__loan_intent_HOMEIMPROVEMENT,20745.0,1.078332e-01,0.310177,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__loan_intent_MEDICAL,20745.0,1.866956e-01,0.389676,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__loan_intent_PERSONAL,20745.0,1.679441e-01,0.373826,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__loan_intent_VENTURE,20745.0,1.794649e-01,0.383750,0.000000,0.000000,0.000000,0.000000,1.000000
categorical__cb_person_default_on_file_N,20745.0,8.234273e-01,0.381316,0.000000,1.000000,1.000000,1.000000,1.000000
categorical__cb_person_default_on_file_Y,20745.0,1.765727e-01,0.381316,0.000000,0.000000,0.000000,0.000000,1.000000

In [50]:
print("=" * 80)
print("Target Distribution")
print("=" * 80)

print(y_train.value_counts(normalize=True))

================================================================================
Target Distribution
================================================================================
loan_status
0    0.781297
1    0.218703
Name: proportion, dtype: float64